import React from 'react';
import './AccessControl.css'; // Reuse the same CSS file for consistency in styling
import logo from '../assets/MachaLogo.png';  // Adjust the path relative to the current file location

// section 6

function SIEMSolutionsPage() {
  const handleButtonClick = (section) => {
    console.log(`Button clicked for: ${section}`);
    // Add logic for handling button click, e.g., open a modal or navigate
  };

  return (
    <div className="form-page">
      {/* Header Section */}
      <header className="header">
        <button className="back-button" onClick={() => window.history.back()}>←</button> {/* Use window.history.back for navigation */}
        <h1>The MACHA Group</h1>
        <img src={logo} alt="Logo" className="logo" />
      </header>

      {/* SIEM Solutions Section */}
      <main className="form-container">
        <h2>Security Information and Event Management (SIEM) Solutions</h2>
        <form>
          {/* Deployment and Integration Section */}
          <h3>Deployment and Integration</h3>

          <div className="form-section">
            <label>How is the SIEM solution integrated with other security systems and tools within the organization (e.g., firewalls, intrusion detection systems)?</label>
            <div>
              <input type="text" name="siemIntegration" placeholder="Describe SIEM integration with other systems" />
            </div>
          </div>

          <div className="form-section">
            <label>What is the scope of the SIEM deployment, and does it cover all critical systems, applications, and network segments?</label>
            <div>
              <input type="text" name="siemScope" placeholder="Describe the scope of SIEM deployment" />
            </div>
          </div>

          <div className="form-section">
            <label>Are there any gaps in coverage or areas where SIEM integration is lacking?</label>
            <div>
              <input type="text" name="siemGaps" placeholder="Describe gaps or lack of SIEM integration" />
            </div>
          </div>

          {/* Event Collection and Correlation Section */}
          <h3>Event Collection and Correlation</h3>

          <div className="form-section">
            <label>What types of security events and logs are collected by the SIEM solution (e.g., network traffic, system logs, application logs)?</label>
            <div>
              <input type="text" name="eventCollection" placeholder="Describe types of logs and events collected" />
            </div>
          </div>

          <div className="form-section">
            <label>How does the SIEM solution correlate events from different sources to identify potential security incidents or threats?</label>
            <div>
              <input type="text" name="eventCorrelation" placeholder="Describe event correlation methods" />
            </div>
          </div>

          <div className="form-section">
            <label>Are there specific rules or algorithms used to prioritize and filter events based on their severity or relevance?</label>
            <div>
              <input type="text" name="eventFiltering" placeholder="Describe rules or algorithms for event filtering" />
            </div>
          </div>

          {/* Real-time Monitoring and Alerts Section */}
          <h3>Real-time Monitoring and Alerts</h3>

          <div className="form-section">
            <label>Does the SIEM solution provide real-time monitoring and alerting capabilities for detected security events and incidents?</label>
            <div>
              <input type="text" name="realTimeMonitoring" placeholder="Describe real-time monitoring and alerts" />
            </div>
          </div>

          <div className="form-section">
            <label>How are alerts configured and managed to minimize false positives and ensure timely detection of genuine threats?</label>
            <div>
              <input type="text" name="alertManagement" placeholder="Describe how alerts are managed" />
            </div>
          </div>

          <div className="form-section">
            <label>What is the process for responding to and investigating alerts generated by the SIEM solution?</label>
            <div>
              <input type="text" name="alertResponse" placeholder="Describe alert response and investigation process" />
            </div>
          </div>

          {/* Incident Detection and Response Section */}
          <h3>Incident Detection and Response</h3>

          <div className="form-section">
            <label>How effective is the SIEM solution in detecting and identifying various types of security incidents (e.g., malware infections, unauthorized access)?</label>
            <div>
              <input type="text" name="incidentDetectionEffectiveness" placeholder="Describe SIEM's effectiveness in incident detection" />
            </div>
          </div>

          <div className="form-section">
            <label>Are there predefined incident response procedures and workflows integrated with the SIEM solution to guide the response to detected incidents?</label>
            <div>
              <input type="text" name="incidentResponseWorkflows" placeholder="Describe predefined incident response workflows" />
            </div>
          </div>

          <div className="form-section">
            <label>How is the effectiveness of incident detection and response measured and evaluated?</label>
            <div>
              <input type="text" name="incidentEffectivenessEvaluation" placeholder="Describe how incident detection and response is evaluated" />
            </div>
          </div>

          {/* Data Storage and Retention Section */}
          <h3>Data Storage and Retention</h3>

          <div className="form-section">
            <label>What is the policy for data storage and retention within the SIEM solution, including the duration for retaining logs and security events?</label>
            <div>
              <input type="text" name="dataRetentionPolicy" placeholder="Describe data storage and retention policy" />
            </div>
          </div>

          <div className="form-section">
            <label>How is the integrity and confidentiality of stored data maintained to prevent unauthorized access or tampering?</label>
            <div>
              <input type="text" name="dataIntegritySecurity" placeholder="Describe data integrity and security measures" />
            </div>
          </div>

          <div className="form-section">
            <label>Are there processes in place for securely archiving or deleting outdated or obsolete data?</label>
            <div>
              <input type="text" name="dataArchiving" placeholder="Describe processes for archiving or deleting outdated data" />
            </div>
          </div>

          {/* Reporting and Analysis Section */}
          <h3>Reporting and Analysis</h3>

          <div className="form-section">
            <label>What types of reports and dashboards are available through the SIEM solution, and how are they used for security analysis and decision-making?</label>
            <div>
              <input type="text" name="reportsAndDashboards" placeholder="Describe types of reports and dashboards available" />
            </div>
          </div>

          <div className="form-section">
            <label>How often are reports generated, and are they reviewed by security personnel or management to assess the overall security posture?</label>
            <div>
              <input type="text" name="reportReviewProcess" placeholder="Describe report generation and review process" />
            </div>
          </div>

          <div className="form-section">
            <label>Are there capabilities for customizing reports and analysis to address specific security concerns or requirements?</label>
            <div>
              <input type="text" name="customReports" placeholder="Describe customization capabilities for reports" />
            </div>
          </div>

          {/* Maintenance and Improvement Section */}
          <h3>Maintenance and Improvement</h3>

          <div className="form-section">
            <label>What is the process for maintaining and updating the SIEM solution, including applying patches, updates, and new threat intelligence feeds?</label>
            <div>
              <input type="text" name="siemMaintenance" placeholder="Describe maintenance and update process for SIEM" />
            </div>
          </div>

          <div className="form-section">
            <label>How is the SIEM solution evaluated for effectiveness, and are there regular assessments or audits to ensure its continued relevance and performance?</label>
            <div>
              <input type="text" name="siemEvaluation" placeholder="Describe SIEM solution evaluation and audits" />
            </div>
          </div>

          <div className="form-section">
            <label>Are there plans for upgrading or expanding the SIEM solution to enhance its capabilities or address emerging security threats?</label>
            <div>
              <input type="text" name="siemUpgradePlans" placeholder="Describe plans for upgrading or expanding the SIEM solution" />
            </div>
          </div>

          {/* Submit Button */}
          <div className="form-section">
            <button type="submit" onClick={() => handleButtonClick('siemSolutions')}>Submit Report</button>
          </div>
        </form>
      </main>
    </div>
  );
}

export default SIEMSolutionsPage;
