import React from 'react';
import './AccessControl.css'; // Reuse the same CSS file for consistency in styling
import logo from '../assets/MachaLogo.png';  // Adjust the path relative to the current file location

// section 6 

function SignatureBasedDetectionPage() {
  const handleButtonClick = (section) => {
    console.log(`Button clicked for: ${section}`);
    // Add logic for handling button click, like opening a modal or navigating
  };

  return (
    <div className="form-page">
      {/* Header Section */}
      <header className="header">
        <button className="back-button" onClick={() => window.history.back()}>←</button> {/* Go back button */}
        <h1>The MACHA Group</h1>
        <img src={logo} alt="Logo" className="logo" />
      </header>

      {/* Signature-Based Detection Section */}
      <main className="form-container">
        <h2>Signature-Based Detection</h2>
        <form>
          {/* Signature Database Management */}
          <h3>Signature Database Management</h3>

          <div className="form-section">
            <label>How frequently is the signature database updated to include the latest known attack patterns and vulnerabilities?</label>
            <div>
              <input type="text" name="signatureUpdateFrequency" placeholder="Describe signature database update frequency" />
            </div>
          </div>

          <div className="form-section">
            <label>What sources are used to gather new signatures for the IDS, and how is the credibility and reliability of these sources ensured?</label>
            <div>
              <input type="text" name="signatureSources" placeholder="Describe sources of new signatures" />
            </div>
          </div>

          <div className="form-section">
            <label>Are there mechanisms in place to create custom signatures based on specific threats faced by the organization?</label>
            <div>
              <input type="text" name="customSignatures" placeholder="Describe mechanisms for creating custom signatures" />
            </div>
          </div>

          {/* Detection Accuracy and Coverage */}
          <h3>Detection Accuracy and Coverage</h3>

          <div className="form-section">
            <label>How comprehensive is the IDS in detecting a wide range of known attack patterns, including zero-day vulnerabilities and emerging threats?</label>
            <div>
              <input type="text" name="comprehensiveDetection" placeholder="Describe the comprehensiveness of the IDS" />
            </div>
          </div>

          <div className="form-section">
            <label>What measures are in place to balance detection accuracy with performance, ensuring the IDS does not overly tax network resources?</label>
            <div>
              <input type="text" name="accuracyPerformanceBalance" placeholder="Describe measures balancing accuracy and performance" />
            </div>
          </div>

          <div className="form-section">
            <label>Are there any gaps in signature coverage for specific types of attacks or network protocols, and how are these addressed?</label>
            <div>
              <input type="text" name="signatureCoverageGaps" placeholder="Describe any gaps in signature coverage and how they are addressed" />
            </div>
          </div>

          {/* Alerting and Incident Response */}
          <h3>Alerting and Incident Response</h3>

          <div className="form-section">
            <label>How are alerts generated by signature-based detections prioritized, and what criteria determine the severity of an alert?</label>
            <div>
              <input type="text" name="alertPrioritization" placeholder="Describe how signature-based alerts are prioritized" />
            </div>
          </div>

          <div className="form-section">
            <label>What is the standard operating procedure for responding to alerts triggered by known attack patterns, and who is responsible for initiating the response?</label>
            <div>
              <input type="text" name="alertResponseSOP" placeholder="Describe SOP for responding to alerts triggered by known attack patterns" />
            </div>
          </div>

          <div className="form-section">
            <label>Are there measures in place to reduce the occurrence of false positives, and how is the accuracy of alerts verified?</label>
            <div>
              <input type="text" name="falsePositiveReduction" placeholder="Describe measures to reduce false positives" />
            </div>
          </div>

          {/* System Integration and Scalability */}
          <h3>System Integration and Scalability</h3>

          <div className="form-section">
            <label>How well does the signature-based IDS integrate with other cybersecurity tools, such as SIEM (Security Information and Event Management) systems, firewalls, and endpoint protection solutions?</label>
            <div>
              <input type="text" name="systemIntegration" placeholder="Describe integration with other cybersecurity tools" />
            </div>
          </div>

          <div className="form-section">
            <label>Can the IDS scale effectively with the network, accommodating increases in traffic and changes in network architecture without a loss of detection capability?</label>
            <div>
              <input type="text" name="scalability" placeholder="Describe scalability of the IDS" />
            </div>
          </div>

          <div className="form-section">
            <label>How is the IDS configured to handle encrypted traffic, ensuring visibility into potential threats without compromising data privacy?</label>
            <div>
              <input type="text" name="encryptedTrafficHandling" placeholder="Describe how IDS handles encrypted traffic" />
            </div>
          </div>

          {/* Testing and Continuous Improvement */}
          <h3>Testing and Continuous Improvement</h3>

          <div className="form-section">
            <label>How regularly is the effectiveness of signature-based detection tested, and what methods (e.g., penetration testing, red teaming) are used to evaluate its capabilities?</label>
            <div>
              <input type="text" name="detectionTestingFrequency" placeholder="Describe frequency and methods of testing signature-based detection" />
            </div>
          </div>

          <div className="form-section">
            <label>Is there a process for reviewing and refining detection signatures based on feedback from incident investigations and threat intelligence updates?</label>
            <div>
              <input type="text" name="signatureRefinementProcess" placeholder="Describe process for refining detection signatures" />
            </div>
          </div>

          <div className="form-section">
            <label>How are lessons learned from past incidents and detected threats incorporated into the ongoing development and improvement of the signature database?</label>
            <div>
              <input type="text" name="lessonsLearned" placeholder="Describe how lessons learned are incorporated into signature development" />
            </div>
          </div>

          {/* Submit Button */}
          <button type="submit" className="submit-button">Submit</button>
        </form>
      </main>
    </div>
  );
}

export default SignatureBasedDetectionPage;
